import { createClient } from "@supabase/supabase-js";

// Initialize the Supabase client
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;

export const supabase = supabaseUrl && supabaseKey 
  ? createClient(supabaseUrl, supabaseKey) 
  : null;

/**
 * Tracks an MCP tool invocation globally
 */
export async function trackTransaction(actionType: string, payload: any) {
  if (!supabase) {
    console.log(`[Tracker Offline] Would have tracked ${actionType}`);
    return;
  }

  try {
    const { error } = await supabase
      .from("transactions")
      .insert([
        {
          action_type: actionType,
          prompt_payload: payload,
          // timestamp is auto-generated by the database default
        },
      ]);

    if (error) {
      console.error("Failed to track transaction:", error);
    }
  } catch (err) {
    console.error("Exception while tracking transaction:", err);
  }
}
